/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 5.0 */
package tree;

public interface CompiladorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTCOMAND_BLOCK = 1;
  public int JJTCOMAND_LINE = 2;
  public int JJTTYPE = 3;
  public int JJTLOG_OP = 4;
  public int JJTVAR_DECLARATION = 5;
  public int JJTEXP_LOG = 6;
  public int JJTNUM_OP = 7;
  public int JJTEXP_NUM = 8;
  public int JJTFOR_DECLARATION = 9;
  public int JJTOP_IN_THE_SAME_VAR = 10;
  public int JJTASSIGNMENT_VAR = 11;
  public int JJTIF_DECLARATION = 12;
  public int JJTELSE_DECLARATION = 13;
  public int JJTFUNC_NAME = 14;
  public int JJTPARAM_LIST = 15;
  public int JJTFUNC = 16;
  public int JJTCOMAND_BLOCK_FUNC = 17;
  public int JJTRETURN_DECLARATION = 18;
  public int JJTWHILE_DECLARATION = 19;


  public String[] jjtNodeName = {
    "start",
    "comand_block",
    "comand_line",
    "type",
    "log_op",
    "var_declaration",
    "exp_log",
    "num_op",
    "exp_num",
    "for_declaration",
    "op_in_the_same_var",
    "assignment_var",
    "if_declaration",
    "else_declaration",
    "func_name",
    "param_list",
    "func",
    "comand_block_func",
    "return_declaration",
    "while_declaration",
  };
}
/* JavaCC - OriginalChecksum=9e4a0bb41a43a13c8c3c71eaf905f373 (do not edit this line) */
